# https://aka.ms/yaml

resources:
  containers:
  - container: gcc
    #image: gcc:8.3.0
    image: magellan2/gcc8:1.1

variables:
  poolImage: 'ubuntu-latest'

trigger:
- master

stages:
# - stage: pre_build
#   displayName: pre-build stage
#   jobs:
#   - job: versions
#     pool:
#       vmImage: $(poolImage)
#     steps:
#     - script: uname -a
#     - script: gcc --version
#     - script: cmake --version
- stage: build
  jobs:
  - job: Build 
    container: gcc
    pool:
      vmImage: $(poolImage)
    steps:
    - script: uname -a
    - script: gcc --version
    - script: cmake --version
    - script: rm -rf build
    - script: mkdir build
    - script: cd build
    - script: cmake ..
    # - script: make

