# https://aka.ms/yaml

resources:
  containers:
  - container: gcc
    image: gcc:8.3.0

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: pre-build
  displayName: pre-build stage
  jobs:
  - job:
    container: gcc
    steps:
    - script: uname -a
    - script: gcc --version

