# https://aka.ms/yaml

resources:
  containers:
  - container: gcc
    image: gcc:8.3.0

variables:
  poolImage: 'ubuntu-latest'

trigger:
- master

stages:
- stage: pre-build
  displayName: pre-build stage
  jobs:
  - job: versions
    pool:
      vmImage: $(poolImage)
    steps:
    - script: uname -a
    - script: gcc --version
    - script: cmake --version
- stage: Build
  jobs:
  - job: build 
    container: gcc
    pool:
      vmImage: $(poolImage)
    steps:
    - script: rm -rf build
    - script: mkdir build
    - script: cd build
    - script: cmake ..
    - script: make

