# https://aka.ms/yaml

resources:
  containers:
  - container: gcc
    image: gcc:8.3.0

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: pre-build
  displayName: pre-build stage
  jobs:
  - job: versions
    steps:
    - script: uname -a
    - script: gcc --version
    - script: cmake --version
- stage: Build
  jobs:
  - job: build 
    container: gcc
    steps:
    - script: rm -rf build
    - script: mkdir build
    - script: cd build
    - script: cmake ..
    - script: make

